config/routes.rb
Rails.application.routes.draw do
  resources :tags
  # provides all routes required for the controllers actions(Article)
  # eg, /articles, /articles/new, /articles/:id/edit, etc
  resources :articles
  # Non-resourceful  routes for sessions controller

  # Sets route as /signup route instead of /new route for registering a new user
  get 'signup', to: 'users#new'
  # new login form route: GET method for creating a session as login
  get 'login', to: 'sessions#new'
  # login route POST method create the session
  post 'login', to: 'sessions#create'
  # delete route: DELETE method to logout destroy the session
  delete 'logout', to: 'sessions#destroy'

  # post 'users', to: 'users#create'  => only for one route of users resources
  # This method will add all the routes for the users resources except the new action
  resources 'users', except: %i[new]

  # connects the 'pages/home' URL to the Controller pages

  # set the default or root page to render (root route)
  # when we go to 'http://localhost:3000/'
  root 'pages#home'

  # connects the 'pages/about' URL to the Controller pages
  # further to action about
  get 'pages/about', to: 'pages#about'

  # create resourc full routes fot the categories resource except the destroy action
  resources :categories, except: [:destroy]
end

app/models/article.rb
class Article < ApplicationRecord

  # this defines that the article belongs to the user with user_id
  # first Symbol here is the current user, the class name of the model, and the key to which the user is referenced
  # singular name of the virtual reference of the object user
  belongs_to :user

  # Specifies the one - to  - many assiscation betwenn this mmodel and the
  # metiond model
  has_many :article_categories

  # specifies the assicuation throufht which table model query
  # many to many relation is built using method between thhe models article and category
  has_many :categories, through: :article_categories
  has_many :article_tags
  has_many :tags, through: :article_tags
  # validates the attribute before hitting the database
  # generates predefined errors if the validation not met by the attributes
  validates :title, presence: true, length: { minimum: 3, maximum: 20 }
  validates :description, presence: true, length: { minimum: 3, maximum: 300 }
  # adding the validation for user_id (a user must be associated with the articles)
  # before saving into the database
  validates :user_id, presence: true


  # Check is the {User} can edit the article or not
  #
  # @param [User] user
  #
  # @return [Boolean]
  def can_be_edited_by?(user)
    user.admin? || user_id == user.id
  end

end

app/controllers/articles_controller.rb
# Manages the Articles
class ArticlesController < ApplicationController

  # before actions work in order

  # a filter method used tio  controls the action
  # these methods can halt the requests and
  # these methods run before performing the mentioned actions in the only array
  before_action :set_article, only: %i[edit show update destroy]

  # Restrict the physical access through the url links
  # First set the user through the set_user then use the require_user to perform
  # the all actions expect mentioned these actions
  # we will require a user to perform the remaining operations(new, create, edit, update, destroy)
  before_action :require_user, expect: %i[index show]

  # Allow the users who have created the article to edit , :delete update actions
  before_action :require_same_user, only: %i[edit update destroy]

  # This action List creates an instance which stores all the Articles fetched
  # from the persistent database
  #
  # @return [Array<Articles>]
  def index
    # @articles = Article.all

    # performs a pagination here with per page only 5 articles
    @articles = Article.paginate page: params[:page], per_page: 5
    # @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  # UNDERSTANDING: The new action renders new form where we will be
  # entering the data ( title and description )

  # creates a new instance of the article to be added
  #
  # @return [void]
  #
  def new
    @article = Article.new
  end

  # This actions is invoked when the submit button here(Create Article) is
  # clicked this creates a new instance of the Article with the parameters
  # entered by the user in the new form
  # These parameters are whitelisted at first then the parameters hits the
  # database by using @article.save

  # UNDERSTANDING 108927 =
  # sets the success message if article gets saved in the database
  # else the new page is rendered again with empty fields

  # Creates a new instance with the parameters from the form
  #
  # @return [void]
  #
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    # For now hardcoded the user reference to the first user in the database

    # Render validation errors on form if resource is not saved due to invalid
    # data (which did not pass validations defined resource model)
    if @article.save
      flash[:notice] = 'Article Created Successfully'
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  # UNDERSTANDING #108926 = (TASK 1)this action creates and instance for the Article
  # id requested by the user, this and the data is retrieved and sent to the
  # view through the @article instance, this persistent data is then edited
  # in the edit form and then when we hit the update article button the
  # update action is invoked

  # Action to edit the specific article
  #
  # @return [Article]
  def edit
    # (TASK 3) assigning the data by retrieving the persistent data using the :id
    # set_article runs before this methods are  executes
  end

  # UNDERSTANDING #108926 = (TASK 4)After editing the information retrieved  in the edit
  # form the edit update article button is clicked then this update action is
  # invoked this action sets a new instance with the updated information
  # this information is updated in the database using the update method
  # provided by the ActionController and data validation is performed through
  # models validate method

  # Action updates the existing data with the newly entered data
  #
  # @return [void]
  def update
    # set_article runs before this methods are  executes
    # (TASK 4)Collecting the data using params and whitelisting them so as to def update
    # that data into the persistent database
    if @article.update(article_params)
      # (TASK 6) Display the message for successfully updating the Article
      # using flash displayed on the show view of the article
      flash[:notice] = 'Article Updated Successfully!'
      # (TASK 6)After Successfully updating the article redirects to the articles show page
      # article_path is the method provided by the resources which accepts the
      # article instance as the argument +show+ (invokes the show action for id)
      redirect_to article_path(@article)
    else
      # (TASK 5)if the data edited is invalid the same page is rendered again with the
      # errors that is preventing the article from updating
      render 'edit'
    end
  end

  # Shows a specific article
  #
  # @return [Article]
  #
  def show
    # set_article runs before this methods are  executes
  end

  # the destroy action is invoked when the route is specified to the DELETE
  # Http method in this action the @article is assigned the article which
  # is to be deleted this article is then deleted using the destroy method
  # which runs the query for the database that is
  # "delete * from articles where id = @article.id"
  # if no error occurs an this hits the database it will display the success
  # message else some error in this case no error might occur as we are
  # deleting only the articles which are present in the list

  # Assigns a new instance the article to be deleted by finding it using the id
  #
  # @return [Article]
  def destroy
    # set_article runs before this methods are  executes
    @article.destroy
    flash[:notice] = 'Article Deleted Successfully!!'
    redirect_to articles_path
  end

  private

  # the user login and the user of the article must be same
  # Checks whether the user logged in and the articles owner and the current user are name
  # also checks whether the current user is a admin user or not

  # User is the owner of the articles or not
  #
  # @return [void]
  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:danger] = 'You can only delete or edit your own articles.'
      redirect_to root_path
    end
  end

  # Sets the @article to the article that is passed a params form the view
  #
  # @return [Article]
  def set_article
    @article = Article.find(params[:id])
  end

  # This method says that the parameters are required and the parameters are
  # the require method looks for params[:article] and raises error if not
  # present and  the permit method is a list of allowed but optional attributes.

  # whitelists the parameters for further process that is save to database
  #
  # @return [Hash]
  def article_params
    # whitelists the parameters from the view :title, description and :user_id
    params.require(:article).permit(:title, :description, category_ids: [], tags_ids: [])
  end

end

app/views/articles/_article.html.erb
<div class="card center text-center border-primary mb-3" align="center" style="width: 30rem; ">
  <div class="card-header">
    Featured
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= link_to article.title, article_path(article) %></h5>
    <p class="card-text"><%= truncate(article.description, length: 100) %></p>
    <% if article.categories.any? %>
      <p>Categories: <%= render article.categories %></p>
    <% end %>
    <% if article.tags.any? %>
      <p>Tags: <%= render article.tags %></p>
    <% end %>
    <% # Admin and the owner of the article can edit and edit the artile %>
    <% if logged_in? && administrator?(article) %>
      <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-primary" %>
      <%= link_to "Delete this article", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete the article?" }, class: "btn btn-danger" %>
    <% end %>
  </div>
  <div class="card-footer text-muted">
    <small>
      Created by: <%= article.user.username if article.user %>,
      Created <%= time_ago_in_words(article.created_at) %> ago,
      Updated <%= time_ago_in_words(article.updated_at) %> ago
    </small>
  </div>
</div>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<%#
  This is new form for creating a new article in the articles table
 %>
<%# The form_for is a helper method provided by rails to create fields and abels in the html file %>
<div class='col-xs-12'>
  <%= form_for @article do |f| %>
    <div class="form-group row">
      <%#  Lable and text field for accepting the Title of the article %>
      <%= f.label :title, "Title", class: "col-sm-3 col-form-label" %>
      <div class="col-sm-8">
        <%= f.text_field :title, class: "form-control shadow rounded shadow rounded", placeholder: "Title of article", autofocus: true %>
      </div>
    </div>
    <div class="form-group row">
      <%# Label and textarea to accept the description of the Article %>
      <%= f.label :description, "Description", class: "col-sm-3 col-form-label"%>
      <div class="col-sm-8">
        <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Body of article" %>
      </div>
    </div>
    <div class="form-group row">
      <%#  Lable and text field for accepting the Title of the article %>
      <%= f.label :user_id, "User", class: "col-sm-3 col-form-label" %>
      <div class="col-sm-6">
        <%= f.collection_select :category_ids, Category.all, :id, :name, { prompt: "Select Category (Can be empty)"}, {multiple: true, size: 3, class: "form-control shadow rounded custom-select shadow rounded" } %>
      </div>
    </div>
    <div class="form-group row">
      <%#  Lable and text field for accepting the Title of the article %>
      <%= f.label :user_id, "User", class: "col-sm-3 col-form-label" %>
      <div class="col-sm-6">
        <%= f.collection_select :tag_ids, Tag.all, :id, :name, { prompt: "Select Tag (Can be empty)"}, {multiple: true, size: 3, class: "form-control shadow rounded custom-select shadow rounded" } %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-sm-3"></div>
      <div class="col-sm-offset-4 col-sm-5">
        <%# This tag is the submit button after entering the data into the text field and text area this line invokes the create action in the articles controller %>
        <%= f.submit class: 'btn btn-primary' %><br>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-sm-3"></div>
      <div class="col-xs-4 col-xs-offset-4">
        <%= link_to "Cancel request and go Back to the list", articles_path %>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/edit.html.erb
<h2 align="center">Edit the article</h2>
<% # Render the form partial _form.html.erb %>
<%= render "form" %>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>
<% # pagination to display 5 articles per pages %>
<div class="center">
  <%= will_paginate(@articles, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
</div>
<div align="center">
  <%= render @articles %>
</div>
<div class="center">
  <%= will_paginate(@articles, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
</div>

app/views/articles/new.html.erb
<h1 align="center">Create an Article</h1>
<% # Renders the form partial %>
<%= render "form" %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<% # (TASK 1)Render resource information on view created for `show` action on successful creation of resource %>
<% # Shows a particular article details here %>
<div align="center">
  <%= link_to "Show All Articles", articles_path, class: "btn btn-secondary" %>
  <%= render @article %>
</div>