config/routes.rb
Rails.application.routes.draw do
  resources :tags
  # provides all routes required for the controllers actions(Article)
  # eg, /articles, /articles/new, /articles/:id/edit, etc
  resources :articles
  # Non-resourceful  routes for sessions controller

  # Sets route as /signup route instead of /new route for registering a new user
  get 'signup', to: 'users#new'
  # new login form route: GET method for creating a session as login
  get 'login', to: 'sessions#new'
  # login route POST method create the session
  post 'login', to: 'sessions#create'
  # delete route: DELETE method to logout destroy the session
  delete 'logout', to: 'sessions#destroy'

  # post 'users', to: 'users#create'  => only for one route of users resources
  # This method will add all the routes for the users resources except the new action
  resources 'users', except: %i[new]

  # connects the 'pages/home' URL to the Controller pages

  # set the default or root page to render (root route)
  # when we go to 'http://localhost:3000/'
  root 'pages#home'

  # connects the 'pages/about' URL to the Controller pages
  # further to action about
  get 'pages/about', to: 'pages#about'

  # create resourc full routes fot the categories resource except the destroy action
  resources :categories, except: [:destroy]
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :article_tags
  has_many :articles, through: :article_tags
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController


  before_action :require_admin, except: %i[index show]
  # Adds a new Tag to the Blog
  #
  # @return [void]
  def new
    @tag = Tag.new
  end

  # Creates a Tag record
  #
  # @return [void]
  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      flash[:success] = 'Tag successfully created'
      redirect_to @tag
    else
      flash[:error] = 'Something went wrong'
      render 'new'
    end
  end

  # Edits the Tag information
  #
  # @return [void]
  def edit
    @tag = Tag.find(params[:id])
  end

  # Updates the tag in the Blog with data
  #
  # @return [void]
  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      flash[:success] = 'Tag was successfully updated'
      redirect_to @tag
    else
      flash[:error] = 'Something went wrong'
      render 'edit'
    end
  end

  # Finds the {Articles} by Tag
  #
  # @return [void]
  def show
    @tag = Tag.find(params[:id])
  end

  private

  # @return [void]
  def require_admin
    return if logged_in? && current_user.admin?

    flash[:alert] = 'Only admins can perform this action'
    redirect_to tags_path
  end

  # Allow attributes that map to the database properties
  #
  # @return [void]
  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render "shared/errors", obj: @tag %>
      <%= form_with(model: @tag, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :name, "Tag Name", class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
          </div>
        </div>
        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to "[ Cancel and return to articles listing ]", articles_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/tags/_tag.html.erb
<span class="badge"><%= link_to tag.name, tag_path(tag) %>  </span>

app/views/tags/edit.html.erb
<h1 class="text-center mt-4">Edit the Tag</h1>
<%= render "form" %>

app/views/tags/index.html.erb
<h1 class="text-center mt-4">Tags</h1>

<div class="container" align="center">
  <% @tags.each do |tag| %>
    <ul class="list-group">
      <li class="list-group-item d-flex justify-content-between align-items-center mb-2" style:"width: 40px;">
        <%= link_to tag.name, tag_path(tag), class: "text-success" %>
        <span class="badge badge-primary badge-pill"> <%= pluralize(tag.articles.count, " article")%></span>
      </li>
    </ul>
  <% end %>
</div>

app/views/tags/new.html.erb
<h1 class="text-center mt-4">Add new Tag</h1>
<%= render "form" %>

app/views/tags/show.html.erb
<h1 class="text-center mt-4">Tag: <%= @tag.name %></h1>
<% if logged_in? && current_user.admin? %>
    <%= link_to "Edit Tag", edit_tag_path(@tag), class: "badge " %>
  <% end %>
<div align="center">
  <%= render @tag.articles %>
</div>