config/routes.rb
Rails.application.routes.draw do
  resources :tags
  # provides all routes required for the controllers actions(Article)
  # eg, /articles, /articles/new, /articles/:id/edit, etc
  resources :articles
  # Non-resourceful  routes for sessions controller

  # Sets route as /signup route instead of /new route for registering a new user
  get 'signup', to: 'users#new'
  # new login form route: GET method for creating a session as login
  get 'login', to: 'sessions#new'
  # login route POST method create the session
  post 'login', to: 'sessions#create'
  # delete route: DELETE method to logout destroy the session
  delete 'logout', to: 'sessions#destroy'

  # post 'users', to: 'users#create'  => only for one route of users resources
  # This method will add all the routes for the users resources except the new action
  resources 'users', except: %i[new]

  # connects the 'pages/home' URL to the Controller pages

  # set the default or root page to render (root route)
  # when we go to 'http://localhost:3000/'
  root 'pages#home'

  # connects the 'pages/about' URL to the Controller pages
  # further to action about
  get 'pages/about', to: 'pages#about'

  # create resourc full routes fot the categories resource except the destroy action
  resources :categories, except: [:destroy]
end

app/models/category.rb
class Category < ApplicationRecord

  # one to many association betweeen the Category and the article_categories  model
  has_many :article_categories

  # Many to many relation between the article and category model
  # through the article_categories table
  has_many :articles, through: :article_categories

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  # To perform the restfull operations user should be an admin
  before_action :require_admin, except: %i[index show]

  # Renders the create new category form with @user new instance of Category
  #
  # @return [void]
  def new
    @category = Category.new
  end

  # List all the categories
  #
  # @return [void]
  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  # renders the specific category articles_list
  #
  # @return [void]
  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  # Create new categpry and save to the persistent data
  #
  # @return [void]
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category was successfully created'
      redirect_to @category
    else
      render 'new'
    end
  end

  # Render the edit category name form
  #
  # @return [void]
  def edit
    @category = Category.find(params[:id])
  end

  # Save to the persistent data
  #
  # @return [void]
  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = 'Category name was successfully updated'
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  private

  # Sets the parameters for the category nane
  #
  # @return [void]
  def category_params
    params.require(:category).permit(:name)
  end

  # This check for the user is an admin or not, if admin then return else set flash
  # as the message and pass to the next request i.e /categories
  # @return [<Type>] <description>
  def require_admin
    return if logged_in? && current_user.admin?

    flash[:alert] = 'Only admins can perform this action'
    redirect_to categories_path
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %>  </span>

app/views/categories/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render "shared/errors", obj: @category %>
      <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :name, "Category Name", class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
          </div>
        </div>
        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to "[ Cancel and return to articles listing ]", articles_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit Catedory Name</h1>
<%= render "form" %>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>
<div class="flickr_pagination mb-4">
  <%= will_paginate(@categories , renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
</div>
<div class="container" align="center">
  <% @categories.each do |category| %>
    <ul class="list-group">
      <li class="list-group-item d-flex justify-content-between align-items-center mb-2" style:"width: 40px;">
        <%= link_to category.name, category_path(category), class: "text-success" %>
        <span class="badge badge-primary badge-pill"> <%= pluralize(category.articles.count, " article")%></span>
      </li>
    </ul>
  <% end %>
</div>
<div class="flickr_pagination mt-4">
  <%= will_paginate(@categories , renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">Create new Category</h1>
<%= render "form" %>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %></h1>
<div class="flickr_pagination">
  <% if logged_in? && current_user.admin? %>
    <%= link_to "Edit Category Name", edit_category_path(@category), class: "badge " %>
  <% end %>
  <%= will_paginate @category_articles, :container => false %>
</div>
<%= render @category_articles %>
<div class="flickr_pagination mb-4">
  <%= will_paginate @category_articles, :container => false %>
</div>