config/routes.rb
Rails.application.routes.draw do
  resources :tags
  # provides all routes required for the controllers actions(Article)
  # eg, /articles, /articles/new, /articles/:id/edit, etc
  resources :articles
  # Non-resourceful  routes for sessions controller

  # Sets route as /signup route instead of /new route for registering a new user
  get 'signup', to: 'users#new'
  # new login form route: GET method for creating a session as login
  get 'login', to: 'sessions#new'
  # login route POST method create the session
  post 'login', to: 'sessions#create'
  # delete route: DELETE method to logout destroy the session
  delete 'logout', to: 'sessions#destroy'

  # post 'users', to: 'users#create'  => only for one route of users resources
  # This method will add all the routes for the users resources except the new action
  resources 'users', except: %i[new]

  # connects the 'pages/home' URL to the Controller pages

  # set the default or root page to render (root route)
  # when we go to 'http://localhost:3000/'
  root 'pages#home'

  # connects the 'pages/about' URL to the Controller pages
  # further to action about
  get 'pages/about', to: 'pages#about'

  # create resourc full routes fot the categories resource except the destroy action
  resources :categories, except: [:destroy]
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <footer class="footer">
    <div class="container">
      <small>
        Copyright © <a href="http://projects.allerin.com/issues/108948">Application Development Training</a>
        by <%= link_to "Shubham Taywade", "http://projects.allerin.com/issues/108948" %>
      </small>
      <nav>
        <ul>
          <li><%= link_to "About", pages_about_path %></li>
        </ul>
      </nav>
    </div>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<%# Renders flash notice on view on creating new resource as explained in the notes  %>
<div class="container">
  <% flash.each do |name, msg| %>
    <div class='alert alert-<%="#{name}"%> alert-dismissible fade show' role="alert" >
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <%= link_to "NEUTRON BLOG", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Bloggers", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Articles
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View Articles", articles_path, class: "dropdown-item" %>
            <% if logged_in? %>
              <%= link_to "Create new Article", new_article_path, class: "dropdown-item" %>
            <% end %>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Categories
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View Categories", categories_path, class: "dropdown-item" %>
            <% if logged_in? && current_user.admin? %>
              <%= link_to "Create new Categories", new_category_path, class: "dropdown-item" %>
            <% end %>
          </div>
        </li>
      </ul>
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.username %><%= "(Admin)" if current_user.admin? %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "View Profile", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Edit Profile", edit_user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Delete Profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?" } %>
            </div>
          </li>
        <% end %>
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to "Log out", logout_path, class: "btn btn-danger mr-3", method: :delete %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", login_path, class: "btn btn-primary mr-3" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", signup_path, class: "btn btn-success" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NeutronBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <%# Renders the messages partial to display any flash messages available %>
    <%= render 'layouts/messages'%>
    <div class="container">
      <%= yield %>
      <%# This tag displays the Paramaters using the byebug gem Debugging %>
      <%# debug(params) if Rails.env.development? %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>